### ISSUE TITLE
read() timeout should be in seconds

### ISSUE THREAD

**Issue by eliotb** [Kvaser/canlib-samples#2]
Timeouts in python are usually in floating point seconds.   For a while I thought the read timeout was broken, until I realised it was in milliseconds like the C API.

I'd prefer if this parameter was changed to seconds in the python API. (you could document this in C doxygen with a python-specific note)

or, if you didn't want to do this, at least change the parameter name to timeout_millisec

**Comment by Cecron** [comment]
I understand the idea of seconds, but I guess we just rename it to timeout_ms to not break compatibility...

**Comment by eliotb** [comment]
On 03/09/15 21:34, Cecron wrote:
> I understand the idea of seconds, but I guess we just rename it to
> timeout_ms to not break compatibility...

Actually, renaming the parameter WILL break backward compatibility.

I.e if someone has read(timeout=10000) in their code, this will break.

All you can do is correct the docstring

(Actually would be good to have docstrings for at least the 10 core API
methods)

**Comment by Cecron** [comment]
What was I thinking, reverting. :-(
Yes, docstrings are on the wishlist.
